basePath: /api/v1
host: localhost:3000
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.swagger.io/support
  description: Go Quiz - A dynamic, community-driven learning platform
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GoQuiz API
  version: "1.0"
paths: {}
schemes:
- http
- https
securityDefinitions:
  Bearer:
    description: '"Type ''Bearer TOKEN'' to correctly set the API Key"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
